jobs:

 - name: weekdays
   schedule: 0 1 * * 1 # The will run every monday at 1:00am.
   steps:
     - name: installation packages
       command: dbt deps
     - name: run snapshot
       command: dbt snapshot
     - name: run models
       command: dbt run
     - name: test model
       command: dbt test