version: 2

sources:
  - name: snowflake_sample_data
    database: snowflake_sample_data
    description: "A sample database from Snowflake"
    schema: TPCDS_SF10TCL 
    tables:
      - name: store_sales
        description: "Details about the sales in the store"
    
  - name: gokulDB
    database: GOKULDB
    description: "A sample database from Snowflake"
    schema: PUBLIC 
    tables:
      - name: teams
        description: "Details about the teams in NBA"
        